"""The sole dependency-free public interface of the authorization module."""

from .action_ids import ActionId, PermissionId, action_id, permission_id
from .adapter_bindings import (
    AdapterBindingCreateFacts,
    AdapterBindingAuthorizationPort,
    AdapterBindingMutationAuthorityFacts,
    AdapterBindingReadFacts,
    AdapterBindingResumeFacts,
    AdapterBindingSuspendFacts,
    adapter_binding_resource_digest,
)
from .contribution_policies import (
    ContributionPolicyAuthorizationPort,
    ContributionPolicyMutationAuthorityFacts,
    ContributionPolicyCreateDraftFacts,
    ContributionPolicyPublishFacts,
    ContributionPolicyReadFacts,
    ContributionPolicyRetireFacts,
    ContributionPolicyUpdateDraftFacts,
    contribution_policy_resource_digest,
)
from .decisions import AuthorizationDecision, DecisionOutcome
from .errors import (
    AuthorizationBoundaryError,
    AuthorizationDenied,
    AuthorizationUnavailable,
    PreparedAuthorizationInvalid,
)
from .facts import ActorIdentityFacts, ActorKind, JsonScalar, ResourceFacts, ResourceValue
from .ports import AuthorizationPort, PreparedAuthorizationPort, PreparedHandleT
from .project_guide_compilation import (
    ProjectGuideCompilationAuthorizationPort,
    ProjectGuideCompilationExecutePersistFacts,
    ProjectGuideCompilationExecutePreflightFacts,
    ProjectGuideCompilationRequestFacts,
    ProjectGuideCompilationRequestOrigin,
    project_guide_compilation_automatic_request_authority_digest,
    project_guide_compilation_execute_resource_digest,
    project_guide_compilation_facts_digest,
    project_guide_compilation_request_authority_digest,
    project_guide_compilation_request_resource_digest,
)
from .project_guide_projections import (
    ArtifactPolicyProjectionAuthorizationPort,
    ArtifactPolicyProjectionFacts,
    GuideSufficiencyProjectionAuthorizationPort,
    GuideSufficiencyProjectionFacts,
    PreparedArtifactPolicyProjection,
    PreparedGuideSufficiencyProjection,
    ProjectGuideProjectionAuthorityReceipt,
    ProjectGuideProjectionIdentity,
    ProjectGuideProjectionLocator,
    artifact_policy_projection_facts_digest,
    artifact_policy_projection_identity,
    guide_sufficiency_projection_facts_digest,
    guide_sufficiency_projection_identity,
    projection_authority_digest,
)

from .project_setup_finalization import (
    FINALIZATION_ACTION,
    FINALIZATION_PERMISSION,
    FINALIZATION_RESOURCE,
    FINALIZATION_SERVICE,
    PreparedSetupFinalization,
    ProjectSetupFinalizationAuthorityReceipt,
    ProjectSetupFinalizationFacts,
    ProjectSetupFinalizationLocator,
    SetupFinalizationAuthorizationPort,
    setup_finalization_authority_digest,
    setup_finalization_fact_values,
    setup_finalization_facts_digest,
    setup_finalization_identity,
)

__all__ = (
    "FINALIZATION_ACTION",
    "FINALIZATION_PERMISSION",
    "FINALIZATION_RESOURCE",
    "FINALIZATION_SERVICE",
    "PreparedSetupFinalization",
    "ProjectSetupFinalizationAuthorityReceipt",
    "ProjectSetupFinalizationFacts",
    "ProjectSetupFinalizationLocator",
    "SetupFinalizationAuthorizationPort",
    "setup_finalization_authority_digest",
    "setup_finalization_fact_values",
    "setup_finalization_facts_digest",
    "setup_finalization_identity",

    "ActionId",
    "AdapterBindingCreateFacts",
    "AdapterBindingAuthorizationPort",
    "AdapterBindingMutationAuthorityFacts",
    "AdapterBindingReadFacts",
    "AdapterBindingResumeFacts",
    "AdapterBindingSuspendFacts",
    "ActorIdentityFacts",
    "ActorKind",
    "AuthorizationBoundaryError",
    "AuthorizationDecision",
    "AuthorizationDenied",
    "AuthorizationPort",
    "AuthorizationUnavailable",
    "ContributionPolicyAuthorizationPort",
    "ContributionPolicyMutationAuthorityFacts",
    "ContributionPolicyCreateDraftFacts",
    "ContributionPolicyPublishFacts",
    "ContributionPolicyReadFacts",
    "ContributionPolicyRetireFacts",
    "ContributionPolicyUpdateDraftFacts",
    "DecisionOutcome",
    "JsonScalar",
    "PermissionId",
    "PreparedAuthorizationInvalid",
    "PreparedAuthorizationPort",
    "PreparedHandleT",
    "ProjectGuideCompilationAuthorizationPort",
    "ProjectGuideCompilationExecutePersistFacts",
    "ProjectGuideCompilationExecutePreflightFacts",
    "ProjectGuideCompilationRequestFacts",
    "ProjectGuideCompilationRequestOrigin",
    "project_guide_compilation_automatic_request_authority_digest",
    "ArtifactPolicyProjectionAuthorizationPort",
    "ArtifactPolicyProjectionFacts",
    "GuideSufficiencyProjectionAuthorizationPort",
    "GuideSufficiencyProjectionFacts",
    "PreparedArtifactPolicyProjection",
    "PreparedGuideSufficiencyProjection",
    "ProjectGuideProjectionAuthorityReceipt",
    "ProjectGuideProjectionIdentity",
    "ProjectGuideProjectionLocator",
    "artifact_policy_projection_facts_digest",
    "artifact_policy_projection_identity",
    "guide_sufficiency_projection_facts_digest",
    "guide_sufficiency_projection_identity",
    "projection_authority_digest",
    "project_guide_compilation_execute_resource_digest",
    "project_guide_compilation_facts_digest",
    "project_guide_compilation_request_authority_digest",
    "project_guide_compilation_request_resource_digest",
    "ResourceFacts",
    "ResourceValue",
    "action_id",
    "adapter_binding_resource_digest",
    "contribution_policy_resource_digest",
    "permission_id",
)
