"""Closed product capabilities owned by artifact orchestration."""

from __future__ import annotations

from collections.abc import AsyncIterable
from dataclasses import dataclass
from typing import Literal, Protocol
from uuid import UUID

from app.modules.authorization.prepared import PreparedAuthorizationHandle
from app.modules.authorization.runtime import AuthorizationContext
from app.modules.checkers.api.output_custody import CheckerOutputSelector

__all__ = (
    "ArtifactAuditResourceType",
    "ArtifactBindingResourceType",
    "ArtifactBindingPort",
    "ArtifactOperatorReadPort",
    "ArtifactOperatorRecoveryPort",
    "ArtifactRecoveryRequest",
    "CheckerArtifactOutputPort",
    "CheckerOutputBindingRequest",
    "CheckerOutputArtifactRequest",
    "CheckerOutputArtifactResult",
    "CheckerOutputBindingResult",
    "GuideArtifactIngestPort",
    "GuideArtifactIngestCommand",
    "GuideArtifactIngestRequest",
    "GuideArtifactIngestResult",
)


ArtifactBindingResourceType = Literal[
    "project",
    "project_guide",
    "guide_source_snapshot",
    "guide_source_snapshot_item",
    "task",
    "submission",
    "checker_run",
]
ArtifactAuditResourceType = Literal[
    "artifact_binding",
    "artifact_content",
    "artifact_replica",
    "artifact_receipt",
    "artifact_verification_job",
    "artifact_recovery_attempt",
]


@dataclass(frozen=True, slots=True)
class GuideArtifactIngestRequest:
    """Prepared guide-source authority and canonical product ownership."""

    prepared_authorization: PreparedAuthorizationHandle
    project_id: UUID
    guide_id: UUID
    guide_source_snapshot_id: UUID
    source_item_id: UUID
    operation_identity: str
    request_digest: str
    logical_role: str
    byte_source: AsyncIterable[bytes]


@dataclass(frozen=True, slots=True)
class GuideArtifactIngestResult:
    """Durable identity returned without exposing provider coordinates."""

    put_attempt_id: UUID
    operation_identity: str
    sha256: str
    byte_count: int
    status: str
    replayed: bool


@dataclass(frozen=True, slots=True)
class CheckerOutputBindingRequest:
    """Bind one exact independently verified output in the caller transaction."""

    selector: CheckerOutputSelector
    put_attempt_id: UUID
    verification_receipt_id: UUID


@dataclass(frozen=True, slots=True)
class CheckerOutputArtifactRequest:
    """Bounded generated bytes; action authority is freshly prepared by ART."""

    selector: CheckerOutputSelector
    byte_source: AsyncIterable[bytes]


@dataclass(frozen=True, slots=True)
class CheckerOutputArtifactResult:
    """Durable put identity and verified custody, without provider coordinates."""

    put_attempt_id: UUID
    status: str
    content_id: UUID | None
    verification_receipt_id: UUID | None
    replayed: bool


@dataclass(frozen=True, slots=True)
class CheckerOutputBindingResult:
    """Immutable binding participating in the caller's final-result transaction."""

    binding_id: UUID
    content_id: UUID
    put_attempt_id: UUID
    verification_receipt_id: UUID
    replayed: bool


@dataclass(frozen=True, slots=True)
class ArtifactRecoveryRequest:
    """Reason-bound Operator retry of one exact verification job."""

    authorization_context: AuthorizationContext
    project_id: UUID
    task_id: UUID
    submission_id: UUID | None
    source_verification_job_id: UUID
    reason: str
    client_idempotency_key: str
    expected_source_job_cas_version: int


class GuideArtifactIngestPort(Protocol):
    """Ingest authorized guide bytes without exposing provider operations."""

    async def ingest(self, request: GuideArtifactIngestRequest) -> GuideArtifactIngestResult:
        """Ingest one canonical guide source item."""


class GuideArtifactIngestCommand(Protocol):
    """Route-facing preflight that owns one request-local PREP lifecycle."""

    async def ingest(
        self,
        *,
        authorization_context: AuthorizationContext,
        project_id: UUID,
        guide_id: UUID,
        source_item_id: UUID,
        idempotency_key: UUID,
        content_type: str,
        content_length: int | None,
        byte_source: AsyncIterable[bytes],
    ) -> GuideArtifactIngestResult:
        """Prepare authority before delegating to durable byte ingestion."""


class ArtifactBindingPort(Protocol):
    """Create exact action-bound bindings from verified content."""

    async def bind_checker_output(self, request: CheckerOutputBindingRequest) -> CheckerOutputBindingResult:
        """Bind verified checker output under the checker binding action."""


class CheckerArtifactOutputPort(Protocol):
    """Store generated output for one fixed checker execution."""

    async def store(self, request: CheckerOutputArtifactRequest) -> CheckerOutputArtifactResult:
        """Store one generated checker artifact."""

    async def recover(self, selector: CheckerOutputSelector) -> CheckerOutputArtifactResult | None:
        """Recover a lost output response without a byte source or regeneration."""


class ArtifactOperatorReadPort(Protocol):
    """Expose bounded Operator reads without provider references."""

    async def list_bindings(
        self,
        *,
        authorization_context: AuthorizationContext,
        resource_type: ArtifactBindingResourceType,
        resource_id: UUID,
        cursor: str | None,
        limit: int,
    ) -> object:
        """List bindings for one exact canonical product resource."""

    async def list_replicas(
        self,
        *,
        authorization_context: AuthorizationContext,
        content_id: UUID,
        cursor: str | None,
        limit: int,
    ) -> object:
        """List replicas for one exact Workstream content identity."""

    async def list_receipts(
        self,
        *,
        authorization_context: AuthorizationContext,
        replica_id: UUID,
        cursor: str | None,
        limit: int,
    ) -> object:
        """List receipts for one exact Workstream replica identity."""

    async def get_verification_job(
        self,
        *,
        authorization_context: AuthorizationContext,
        verification_job_id: UUID,
    ) -> object:
        """Read one exact verification job."""

    async def get_recovery_attempt(
        self,
        *,
        authorization_context: AuthorizationContext,
        recovery_attempt_id: UUID,
    ) -> object:
        """Read one exact recovery attempt."""

    async def list_audit_events(
        self,
        *,
        authorization_context: AuthorizationContext,
        resource_type: ArtifactAuditResourceType,
        resource_id: UUID,
        cursor: str | None,
        limit: int,
    ) -> object:
        """List bounded artifact audit events for one exact resource."""

    async def admission_usage(
        self,
        *,
        authorization_context: AuthorizationContext,
        project_id: UUID | None,
        task_id: UUID | None,
        cursor: str | None,
        limit: int,
    ) -> object:
        """Read bounded reserved/completed byte usage and configured limits."""


class ArtifactOperatorRecoveryPort(Protocol):
    """Expose only reason-bound verification retry to Operators."""

    async def retry_verification(self, request: ArtifactRecoveryRequest) -> object:
        """Retry one exact source verification job under CAS fencing."""
